### ISSUE TITLE
What is the noise level when you test the images?

### ISSUE THREAD

**Issue by ysnan** [subeeshvasu/2018_subeesh_nbd_cvpr#1]
Hi, I am confused by how you generated the test images by adding AWG noise. In your supplementary material, you mention the training data is generated by adding up to 2% AWG noise. How about test data? Are you using the same settings or without adding noise for test? 

Thank you!

**Comment by subeeshvasu** [comment]
Hi, 
Since we wanted to have the analysis purely based on kernel noise, we have not added any noise in the test data. Image noise of 2% was added during training mainly to respect the noise effects present in the real images. The impact of this noise addition will be visible only on the real images presented in the paper I guess. 
Cheers.

**Comment by ysnan** [comment]
Got it! Thank you for your prompt and detailed response. Have a nice day!
